
-- LuaLS-only WoW global declarations moved from .luarc.json.
_G = _G
Enum = Enum
ActionButtonUtil = ActionButtonUtil
ActionButton_CalculateAction = ActionButton_CalculateAction
ActionButton_GetPagedID = ActionButton_GetPagedID
AuraUtil = AuraUtil
BuffBarCooldownViewer = BuffBarCooldownViewer
BuffIconCooldownViewer = BuffIconCooldownViewer
ChatFontNormal = ChatFontNormal
C_AddOns = C_AddOns
C_Container = C_Container
C_CooldownViewer = C_CooldownViewer
C_Navigation = C_Navigation
C_TooltipInfo = C_TooltipInfo
C_EquipmentSet = C_EquipmentSet
C_Item = C_Item
C_Spell = C_Spell
C_Timer = C_Timer
C_UnitAuras = C_UnitAuras
CPAPI = CPAPI
AbbreviateNumbers = AbbreviateNumbers
ClearAction = ClearAction
ClearCursor = ClearCursor
CloseAllBags = CloseAllBags
CreateFrame = CreateFrame
ContainerFrameUtil_EnumerateContainerFrames = ContainerFrameUtil_EnumerateContainerFrames
DEFAULT_CHAT_FRAME = DEFAULT_CHAT_FRAME
EnumerateFrames = EnumerateFrames
EssentialCooldownViewer = EssentialCooldownViewer
FCF_IsChatWindowIndexActive = FCF_IsChatWindowIndexActive
GameTooltip = GameTooltip
GetActionInfo = GetActionInfo
GetAddOnMetadata = GetAddOnMetadata
GetBindingAction = GetBindingAction
GetBuildInfo = GetBuildInfo
GetChatWindowInfo = GetChatWindowInfo
GetCVar = GetCVar
GetCursorPosition = GetCursorPosition
GetItemInfo = GetItemInfo
GetItemInfoInstant = GetItemInfoInstant
GetInstanceInfo = GetInstanceInfo
GetItemSpell = GetItemSpell
GetWeaponEnchantInfo = GetWeaponEnchantInfo
GetMacroInfo = GetMacroInfo
GetMacroItem = GetMacroItem
GetMacroSpell = GetMacroSpell
GetRealmName = GetRealmName
GetShapeshiftFormInfo = GetShapeshiftFormInfo
GetTime = GetTime
GetUnitSpeed = GetUnitSpeed
HelpTip = HelpTip
InCombatLockdown = InCombatLockdown
InterfaceOptionsFrame = InterfaceOptionsFrame
InterfaceOptionsFramePanelContainer = InterfaceOptionsFramePanelContainer
InterfaceOptionsFrame_OpenToCategory = InterfaceOptionsFrame_OpenToCategory
IsAddOnLoaded = IsAddOnLoaded
IsFlying = IsFlying
IsInInstance = IsInInstance
IsMounted = IsMounted
IsPlayerSpell = IsPlayerSpell
IsSpellKnown = IsSpellKnown
IsUsableSpell = IsUsableSpell
LibStub = LibStub
Minimap = Minimap
NUM_ACTIONBAR_BUTTONS = NUM_ACTIONBAR_BUTTONS
NUM_CHAT_WINDOWS = NUM_CHAT_WINDOWS
NUM_SHAPESHIFT_SLOTS = NUM_SHAPESHIFT_SLOTS
NUM_SPECIAL_BUTTONS = NUM_SPECIAL_BUTTONS
NUM_STANCE_SLOTS = NUM_STANCE_SLOTS
ObjectiveTrackerFrame = ObjectiveTrackerFrame
PickupAction = PickupAction
PickupItem = PickupItem
PickupMacro = PickupMacro
PlaceAction = PlaceAction
PlayerFrame = PlayerFrame
RegisterStateDriver = RegisterStateDriver
ReloadUI = ReloadUI
Settings = Settings
SetChatWindowAlpha = SetChatWindowAlpha
SetCVar = SetCVar
StanceBar = StanceBar
TotemFrame = TotemFrame
SuperTrackedFrame = SuperTrackedFrame
UIFrameFadeIn = UIFrameFadeIn
UIFrameFadeOut = UIFrameFadeOut
UIErrorsFrame = UIErrorsFrame
UIParent = UIParent
UIParentLoadAddOn = UIParentLoadAddOn
UnitName = UnitName
UnitGUID = UnitGUID
UtilityCooldownViewer = UtilityCooldownViewer
IN_GAME_NAVIGATION_RANGE = IN_GAME_NAVIGATION_RANGE
OKAY = OKAY
STATICPOPUP_NUMDIALOGS = STATICPOPUP_NUMDIALOGS
StaticPopupDialogs = StaticPopupDialogs
StaticPopup_Show = StaticPopup_Show
date = date
hooksecurefunc = hooksecurefunc
issecretvalue = issecretvalue
ipairs = ipairs
next = next
pairs = pairs
select = select
table = table
tonumber = tonumber
tostring = tostring
type = type
unpack = unpack

-- Additional _G fields used via dynamic lookups.
---@class _G
---@field ChatFrameChannelButton any
---@field ChatFrameMenuButton any
---@field ConsolePort any
---@field ConsolePortCrosshair Frame
---@field ConsolePortItemMenu any
---@field ConsolePortActionBarConfig any
---@field ConsolePortTempAbilityFrame any
---@field ConsolePortUIHandle any
---@field CooldownViewerSettings any
---@field GroupLootHistoryFrame any
---@field ImmersionAPI any
---@field ImmersionFrame any
---@field OpenAllMail any
---@field QuickJoinToastButton any
---@field ShapeshiftBarFrame any
---@field StanceBar any
---@field SuperTrackedFrame any
---@field TargetFrame any
---@field TotemFrame any
