---@meta
---@diagnostic disable: lowercase-global

-- LuaLS-only WoW global declarations moved from .luarc.json.
_G = _G
ActionButtonUtil = ActionButtonUtil
ActionButton_CalculateAction = ActionButton_CalculateAction
ActionButton_GetPagedID = ActionButton_GetPagedID
AuraUtil = AuraUtil
BuffBarCooldownViewer = BuffBarCooldownViewer
BuffFrame = BuffFrame
BuffIconCooldownViewer = BuffIconCooldownViewer
C_AddOns = C_AddOns
C_CooldownViewer = C_CooldownViewer
C_Navigation = C_Navigation
C_EquipmentSet = C_EquipmentSet
C_Item = C_Item
C_Spell = C_Spell
C_Timer = C_Timer
C_UnitAuras = C_UnitAuras
AbbreviateNumbers = AbbreviateNumbers
ClearAction = ClearAction
ClearCursor = ClearCursor
CreateFrame = CreateFrame
DEFAULT_CHAT_FRAME = DEFAULT_CHAT_FRAME
EnumerateFrames = EnumerateFrames
EssentialCooldownViewer = EssentialCooldownViewer
FCF_IsChatWindowIndexActive = FCF_IsChatWindowIndexActive
GameTooltip = GameTooltip
GameTooltip_SetDefaultAnchor = GameTooltip_SetDefaultAnchor
GetActionInfo = GetActionInfo
GetChatWindowInfo = GetChatWindowInfo
GetItemInfo = GetItemInfo
GetItemInfoInstant = GetItemInfoInstant
GetItemSpell = GetItemSpell
GetMacroInfo = GetMacroInfo
GetMacroItem = GetMacroItem
GetMacroSpell = GetMacroSpell
GetShapeshiftFormInfo = GetShapeshiftFormInfo
GetTime = GetTime
HelpTip = HelpTip
InCombatLockdown = InCombatLockdown
InterfaceOptionsFrame = InterfaceOptionsFrame
InterfaceOptionsFramePanelContainer = InterfaceOptionsFramePanelContainer
InterfaceOptionsFrame_OpenToCategory = InterfaceOptionsFrame_OpenToCategory
IsAddOnLoaded = IsAddOnLoaded
IsInInstance = IsInInstance
IsMounted = IsMounted
IsPlayerSpell = IsPlayerSpell
IsSpellKnown = IsSpellKnown
IsUsableSpell = IsUsableSpell
LibStub = LibStub
NUM_ACTIONBAR_BUTTONS = NUM_ACTIONBAR_BUTTONS
NUM_CHAT_WINDOWS = NUM_CHAT_WINDOWS
NUM_SHAPESHIFT_SLOTS = NUM_SHAPESHIFT_SLOTS
NUM_SPECIAL_BUTTONS = NUM_SPECIAL_BUTTONS
NUM_STANCE_SLOTS = NUM_STANCE_SLOTS
ObjectiveTrackerFrame = ObjectiveTrackerFrame
ObjectiveTracker_Collapse = ObjectiveTracker_Collapse
ObjectiveTracker_Expand = ObjectiveTracker_Expand
PickupAction = PickupAction
PickupItem = PickupItem
PickupMacro = PickupMacro
PlaceAction = PlaceAction
PlayerFrame = PlayerFrame
RegisterStateDriver = RegisterStateDriver
ReloadUI = ReloadUI
SetChatWindowAlpha = SetChatWindowAlpha
StanceBar = StanceBar
SuperTrackedFrame = SuperTrackedFrame
UIErrorsFrame = UIErrorsFrame
UIParent = UIParent
UIParentLoadAddOn = UIParentLoadAddOn
UnitGUID = UnitGUID
UnitExists = UnitExists
UtilityCooldownViewer = UtilityCooldownViewer
IN_GAME_NAVIGATION_RANGE = IN_GAME_NAVIGATION_RANGE
hooksecurefunc = hooksecurefunc
ipairs = ipairs
next = next
pairs = pairs
select = select
table = table
tonumber = tonumber
tostring = tostring
type = type
unpack = unpack

-- Additional _G fields used via dynamic lookups.
---@class _G
---@field BagsBar any
---@field ChatFrameMenuButton any
---@field ConsolePort any
---@field ConsolePortActionBarConfig any
---@field ConsolePortTempAbilityFrame any
---@field CooldownViewerSettings any
---@field DamageMeter any
---@field GroupLootHistoryFrame any
---@field MicroButtonAndBagsBar any
---@field MicroMenu any
---@field MicroMenuContainer any
---@field ShapeshiftBarFrame any
---@field StanceBar any
---@field SuperTrackedFrame any
---@field TargetFrame any
